/**
 * lib/tools/tailwind-order.ts
 * Official Tailwind CSS class order — sourced from prettier-plugin-tailwindcss.
 * Used by the Tailwind Class Sorter tool.
 */

export const TAILWIND_ORDER: string[] = [
    // Layout
    'container', 'box-border', 'box-content', 'block', 'inline-block', 'inline', 'flex', 'inline-flex',
    'table', 'inline-table', 'table-caption', 'table-cell', 'table-column', 'table-column-group',
    'table-footer-group', 'table-header-group', 'table-row-group', 'table-row', 'flow-root', 'grid',
    'inline-grid', 'contents', 'list-item', 'hidden',
    // Floats
    'float-right', 'float-left', 'float-none', 'clear-left', 'clear-right', 'clear-both', 'clear-none',
    // Isolation
    'isolate', 'isolation-auto',
    // Object fit
    'object-contain', 'object-cover', 'object-fill', 'object-none', 'object-scale-down',
    // Object position
    'object-bottom', 'object-center', 'object-left', 'object-left-bottom', 'object-left-top',
    'object-right', 'object-right-bottom', 'object-right-top', 'object-top',
    // Overflow
    'overflow-auto', 'overflow-hidden', 'overflow-clip', 'overflow-visible', 'overflow-scroll',
    'overflow-x-auto', 'overflow-y-auto', 'overflow-x-hidden', 'overflow-y-hidden',
    'overflow-x-clip', 'overflow-y-clip', 'overflow-x-visible', 'overflow-y-visible',
    'overflow-x-scroll', 'overflow-y-scroll',
    // Overscroll
    'overscroll-auto', 'overscroll-contain', 'overscroll-none',
    'overscroll-x-auto', 'overscroll-x-contain', 'overscroll-x-none',
    'overscroll-y-auto', 'overscroll-y-contain', 'overscroll-y-none',
    // Position
    'static', 'fixed', 'absolute', 'relative', 'sticky',
    // Inset
    'inset-0', 'inset-x-0', 'inset-y-0', 'top-0', 'right-0', 'bottom-0', 'left-0',
    // Visibility
    'visible', 'invisible', 'collapse',
    // Z-index
    'z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50', 'z-auto',
    // Flexbox & Grid
    'basis-0', 'basis-1', 'basis-2', 'basis-3', 'basis-4', 'basis-5', 'basis-6', 'basis-8', 'basis-10',
    'basis-12', 'basis-16', 'basis-20', 'basis-24', 'basis-32', 'basis-40', 'basis-48', 'basis-64',
    'basis-80', 'basis-96', 'basis-auto', 'basis-px', 'basis-0.5', 'basis-1.5', 'basis-2.5', 'basis-3.5',
    'basis-1/2', 'basis-1/3', 'basis-2/3', 'basis-1/4', 'basis-2/4', 'basis-3/4',
    'basis-1/5', 'basis-2/5', 'basis-3/5', 'basis-4/5', 'basis-full',
    'flex-row', 'flex-row-reverse', 'flex-col', 'flex-col-reverse',
    'flex-wrap', 'flex-wrap-reverse', 'flex-nowrap',
    'flex-1', 'flex-auto', 'flex-initial', 'flex-none',
    'grow', 'grow-0', 'shrink', 'shrink-0',
    'order-first', 'order-last', 'order-none',
    'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-5',
    'grid-cols-6', 'grid-cols-7', 'grid-cols-8', 'grid-cols-9', 'grid-cols-10',
    'grid-cols-11', 'grid-cols-12', 'grid-cols-none',
    'col-auto', 'col-span-1', 'col-span-2', 'col-span-3', 'col-span-4', 'col-span-5', 'col-span-6',
    'col-span-7', 'col-span-8', 'col-span-9', 'col-span-10', 'col-span-11', 'col-span-12', 'col-span-full',
    'col-start-1', 'col-start-2', 'col-start-3', 'col-start-4', 'col-start-5', 'col-start-6',
    'col-start-7', 'col-start-8', 'col-start-9', 'col-start-10', 'col-start-11', 'col-start-12', 'col-start-13', 'col-start-auto',
    'col-end-1', 'col-end-2', 'col-end-3', 'col-end-4', 'col-end-5', 'col-end-6',
    'col-end-7', 'col-end-8', 'col-end-9', 'col-end-10', 'col-end-11', 'col-end-12', 'col-end-13', 'col-end-auto',
    'grid-rows-1', 'grid-rows-2', 'grid-rows-3', 'grid-rows-4', 'grid-rows-5', 'grid-rows-6', 'grid-rows-none',
    'row-auto', 'row-span-1', 'row-span-2', 'row-span-3', 'row-span-4', 'row-span-5', 'row-span-6', 'row-span-full',
    'row-start-1', 'row-start-2', 'row-start-3', 'row-start-4', 'row-start-5', 'row-start-6', 'row-start-7', 'row-start-auto',
    'row-end-1', 'row-end-2', 'row-end-3', 'row-end-4', 'row-end-5', 'row-end-6', 'row-end-7', 'row-end-auto',
    'grid-flow-row', 'grid-flow-col', 'grid-flow-dense', 'grid-flow-row-dense', 'grid-flow-col-dense',
    'auto-cols-auto', 'auto-cols-min', 'auto-cols-max', 'auto-cols-fr',
    'auto-rows-auto', 'auto-rows-min', 'auto-rows-max', 'auto-rows-fr',
    'gap-0', 'gap-1', 'gap-2', 'gap-3', 'gap-4', 'gap-5', 'gap-6', 'gap-7', 'gap-8', 'gap-9', 'gap-10',
    'gap-11', 'gap-12', 'gap-14', 'gap-16', 'gap-20', 'gap-24', 'gap-28', 'gap-32', 'gap-36', 'gap-40',
    'gap-44', 'gap-48', 'gap-52', 'gap-56', 'gap-60', 'gap-64', 'gap-72', 'gap-80', 'gap-96', 'gap-px',
    'gap-x-0', 'gap-x-1', 'gap-x-2', 'gap-x-3', 'gap-x-4', 'gap-x-5', 'gap-x-6', 'gap-x-8', 'gap-x-10',
    'gap-x-12', 'gap-x-16', 'gap-x-20', 'gap-x-24', 'gap-x-32', 'gap-x-40', 'gap-x-48', 'gap-x-64', 'gap-x-px',
    'gap-y-0', 'gap-y-1', 'gap-y-2', 'gap-y-3', 'gap-y-4', 'gap-y-5', 'gap-y-6', 'gap-y-8', 'gap-y-10',
    'gap-y-12', 'gap-y-16', 'gap-y-20', 'gap-y-24', 'gap-y-32', 'gap-y-40', 'gap-y-48', 'gap-y-64', 'gap-y-px',
    'justify-start', 'justify-end', 'justify-center', 'justify-between', 'justify-around', 'justify-evenly', 'justify-stretch',
    'justify-items-start', 'justify-items-end', 'justify-items-center', 'justify-items-stretch',
    'justify-self-auto', 'justify-self-start', 'justify-self-end', 'justify-self-center', 'justify-self-stretch',
    'content-normal', 'content-center', 'content-start', 'content-end', 'content-between', 'content-around', 'content-evenly', 'content-stretch',
    'items-start', 'items-end', 'items-center', 'items-baseline', 'items-stretch',
    'self-auto', 'self-start', 'self-end', 'self-center', 'self-stretch', 'self-baseline',
    'place-content-center', 'place-content-start', 'place-content-end', 'place-content-between',
    'place-content-around', 'place-content-evenly', 'place-content-stretch', 'place-content-baseline',
    'place-items-start', 'place-items-end', 'place-items-center', 'place-items-stretch', 'place-items-baseline',
    'place-self-auto', 'place-self-start', 'place-self-end', 'place-self-center', 'place-self-stretch',
    // Spacing
    'p-0', 'p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-7', 'p-8', 'p-9', 'p-10', 'p-11', 'p-12',
    'p-14', 'p-16', 'p-20', 'p-24', 'p-28', 'p-32', 'p-36', 'p-40', 'p-44', 'p-48', 'p-52', 'p-56',
    'p-60', 'p-64', 'p-72', 'p-80', 'p-96', 'p-px', 'p-0.5', 'p-1.5', 'p-2.5', 'p-3.5',
    'px-0', 'px-1', 'px-2', 'px-3', 'px-4', 'px-5', 'px-6', 'px-7', 'px-8', 'px-9', 'px-10',
    'px-12', 'px-14', 'px-16', 'px-20', 'px-24', 'px-28', 'px-32', 'px-36', 'px-40', 'px-44', 'px-48', 'px-px',
    'py-0', 'py-1', 'py-2', 'py-3', 'py-4', 'py-5', 'py-6', 'py-7', 'py-8', 'py-9', 'py-10',
    'py-12', 'py-14', 'py-16', 'py-20', 'py-24', 'py-28', 'py-32', 'py-36', 'py-40', 'py-44', 'py-48', 'py-px',
    'pt-0', 'pt-1', 'pt-2', 'pt-3', 'pt-4', 'pt-5', 'pt-6', 'pt-8', 'pt-10', 'pt-12', 'pt-16', 'pt-20', 'pt-24', 'pt-px',
    'pr-0', 'pr-1', 'pr-2', 'pr-3', 'pr-4', 'pr-5', 'pr-6', 'pr-8', 'pr-10', 'pr-12', 'pr-16', 'pr-20', 'pr-24', 'pr-px',
    'pb-0', 'pb-1', 'pb-2', 'pb-3', 'pb-4', 'pb-5', 'pb-6', 'pb-8', 'pb-10', 'pb-12', 'pb-16', 'pb-20', 'pb-24', 'pb-px',
    'pl-0', 'pl-1', 'pl-2', 'pl-3', 'pl-4', 'pl-5', 'pl-6', 'pl-8', 'pl-10', 'pl-12', 'pl-16', 'pl-20', 'pl-24', 'pl-px',
    'm-0', 'm-1', 'm-2', 'm-3', 'm-4', 'm-5', 'm-6', 'm-7', 'm-8', 'm-9', 'm-10', 'm-11', 'm-12',
    'm-14', 'm-16', 'm-20', 'm-24', 'm-28', 'm-32', 'm-36', 'm-40', 'm-44', 'm-48', 'm-52', 'm-56',
    'm-60', 'm-64', 'm-72', 'm-80', 'm-96', 'm-px', 'm-auto', 'm-0.5', 'm-1.5', 'm-2.5', 'm-3.5',
    'mx-0', 'mx-1', 'mx-2', 'mx-3', 'mx-4', 'mx-5', 'mx-6', 'mx-8', 'mx-10', 'mx-12', 'mx-16', 'mx-20', 'mx-auto', 'mx-px',
    'my-0', 'my-1', 'my-2', 'my-3', 'my-4', 'my-5', 'my-6', 'my-8', 'my-10', 'my-12', 'my-16', 'my-20', 'my-auto', 'my-px',
    'mt-0', 'mt-1', 'mt-2', 'mt-3', 'mt-4', 'mt-5', 'mt-6', 'mt-8', 'mt-10', 'mt-12', 'mt-16', 'mt-20', 'mt-24', 'mt-auto', 'mt-px',
    'mr-0', 'mr-1', 'mr-2', 'mr-3', 'mr-4', 'mr-5', 'mr-6', 'mr-8', 'mr-10', 'mr-12', 'mr-16', 'mr-20', 'mr-24', 'mr-auto', 'mr-px',
    'mb-0', 'mb-1', 'mb-2', 'mb-3', 'mb-4', 'mb-5', 'mb-6', 'mb-8', 'mb-10', 'mb-12', 'mb-16', 'mb-20', 'mb-24', 'mb-auto', 'mb-px',
    'ml-0', 'ml-1', 'ml-2', 'ml-3', 'ml-4', 'ml-5', 'ml-6', 'ml-8', 'ml-10', 'ml-12', 'ml-16', 'ml-20', 'ml-24', 'ml-auto', 'ml-px',
    'space-x-0', 'space-x-1', 'space-x-2', 'space-x-3', 'space-x-4', 'space-x-5', 'space-x-6', 'space-x-8', 'space-x-px', 'space-x-reverse',
    'space-y-0', 'space-y-1', 'space-y-2', 'space-y-3', 'space-y-4', 'space-y-5', 'space-y-6', 'space-y-8', 'space-y-px', 'space-y-reverse',
    // Sizing
    'w-0', 'w-px', 'w-0.5', 'w-1', 'w-1.5', 'w-2', 'w-2.5', 'w-3', 'w-3.5', 'w-4', 'w-5', 'w-6', 'w-7', 'w-8', 'w-9', 'w-10',
    'w-11', 'w-12', 'w-14', 'w-16', 'w-20', 'w-24', 'w-28', 'w-32', 'w-36', 'w-40', 'w-44', 'w-48', 'w-52', 'w-56', 'w-60',
    'w-64', 'w-72', 'w-80', 'w-96', 'w-auto', 'w-1/2', 'w-1/3', 'w-2/3', 'w-1/4', 'w-2/4', 'w-3/4',
    'w-1/5', 'w-2/5', 'w-3/5', 'w-4/5', 'w-1/6', 'w-2/6', 'w-3/6', 'w-4/6', 'w-5/6',
    'w-1/12', 'w-2/12', 'w-3/12', 'w-4/12', 'w-5/12', 'w-6/12', 'w-7/12', 'w-8/12', 'w-9/12', 'w-10/12', 'w-11/12',
    'w-full', 'w-screen', 'w-svw', 'w-lvw', 'w-dvw', 'w-min', 'w-max', 'w-fit',
    'min-w-0', 'min-w-full', 'min-w-min', 'min-w-max', 'min-w-fit',
    'max-w-0', 'max-w-none', 'max-w-xs', 'max-w-sm', 'max-w-md', 'max-w-lg', 'max-w-xl',
    'max-w-2xl', 'max-w-3xl', 'max-w-4xl', 'max-w-5xl', 'max-w-6xl', 'max-w-7xl',
    'max-w-full', 'max-w-min', 'max-w-max', 'max-w-fit', 'max-w-prose', 'max-w-screen-sm',
    'max-w-screen-md', 'max-w-screen-lg', 'max-w-screen-xl', 'max-w-screen-2xl',
    'h-0', 'h-px', 'h-0.5', 'h-1', 'h-1.5', 'h-2', 'h-2.5', 'h-3', 'h-3.5', 'h-4', 'h-5', 'h-6', 'h-7', 'h-8', 'h-9', 'h-10',
    'h-11', 'h-12', 'h-14', 'h-16', 'h-20', 'h-24', 'h-28', 'h-32', 'h-36', 'h-40', 'h-44', 'h-48', 'h-52', 'h-56', 'h-60',
    'h-64', 'h-72', 'h-80', 'h-96', 'h-auto', 'h-1/2', 'h-1/3', 'h-2/3', 'h-1/4', 'h-2/4', 'h-3/4',
    'h-1/5', 'h-2/5', 'h-3/5', 'h-4/5', 'h-full', 'h-screen', 'h-svh', 'h-lvh', 'h-dvh', 'h-min', 'h-max', 'h-fit',
    'min-h-0', 'min-h-full', 'min-h-screen', 'min-h-svh', 'min-h-lvh', 'min-h-dvh', 'min-h-min', 'min-h-max', 'min-h-fit',
    'max-h-0', 'max-h-px', 'max-h-1', 'max-h-2', 'max-h-4', 'max-h-8', 'max-h-16', 'max-h-32', 'max-h-48', 'max-h-64',
    'max-h-96', 'max-h-none', 'max-h-full', 'max-h-screen', 'max-h-svh', 'max-h-lvh', 'max-h-dvh', 'max-h-min', 'max-h-max', 'max-h-fit',
    // Typography
    'font-sans', 'font-serif', 'font-mono',
    'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl',
    'text-6xl', 'text-7xl', 'text-8xl', 'text-9xl',
    'font-thin', 'font-extralight', 'font-light', 'font-normal', 'font-medium', 'font-semibold', 'font-bold', 'font-extrabold', 'font-black',
    'tracking-tighter', 'tracking-tight', 'tracking-normal', 'tracking-wide', 'tracking-wider', 'tracking-widest',
    'leading-none', 'leading-tight', 'leading-snug', 'leading-normal', 'leading-relaxed', 'leading-loose',
    'leading-3', 'leading-4', 'leading-5', 'leading-6', 'leading-7', 'leading-8', 'leading-9', 'leading-10',
    'list-none', 'list-disc', 'list-decimal',
    'text-left', 'text-center', 'text-right', 'text-justify', 'text-start', 'text-end',
    'text-inherit', 'text-current', 'text-transparent', 'text-black', 'text-white',
    'text-slate-50', 'text-slate-100', 'text-slate-200', 'text-slate-300', 'text-slate-400',
    'text-slate-500', 'text-slate-600', 'text-slate-700', 'text-slate-800', 'text-slate-900',
    'text-gray-50', 'text-gray-100', 'text-gray-200', 'text-gray-300', 'text-gray-400',
    'text-gray-500', 'text-gray-600', 'text-gray-700', 'text-gray-800', 'text-gray-900', 'text-gray-950',
    'text-red-400', 'text-red-500', 'text-red-600',
    'text-orange-400', 'text-orange-500', 'text-orange-600',
    'text-amber-400', 'text-amber-500', 'text-amber-600',
    'text-yellow-400', 'text-yellow-500', 'text-yellow-600',
    'text-lime-400', 'text-lime-500', 'text-lime-600',
    'text-green-400', 'text-green-500', 'text-green-600',
    'text-emerald-400', 'text-emerald-500', 'text-emerald-600',
    'text-teal-400', 'text-teal-500', 'text-teal-600',
    'text-cyan-400', 'text-cyan-500', 'text-cyan-600',
    'text-sky-400', 'text-sky-500', 'text-sky-600',
    'text-blue-400', 'text-blue-500', 'text-blue-600',
    'text-indigo-300', 'text-indigo-400', 'text-indigo-500', 'text-indigo-600',
    'text-violet-400', 'text-violet-500', 'text-violet-600',
    'text-purple-300', 'text-purple-400', 'text-purple-500', 'text-purple-600',
    'text-fuchsia-400', 'text-fuchsia-500', 'text-fuchsia-600',
    'text-pink-400', 'text-pink-500', 'text-pink-600',
    'text-rose-400', 'text-rose-500', 'text-rose-600',
    'uppercase', 'lowercase', 'capitalize', 'normal-case',
    'truncate', 'text-ellipsis', 'text-clip',
    'whitespace-normal', 'whitespace-nowrap', 'whitespace-pre', 'whitespace-pre-line', 'whitespace-pre-wrap', 'whitespace-break-spaces',
    'break-normal', 'break-words', 'break-all', 'break-keep',
    'underline', 'overline', 'line-through', 'no-underline',
    'decoration-solid', 'decoration-double', 'decoration-dotted', 'decoration-dashed', 'decoration-wavy',
    'antialiased', 'subpixel-antialiased',
    'italic', 'not-italic', 'ordinal', 'slashed-zero', 'lining-nums', 'oldstyle-nums',
    'proportional-nums', 'tabular-nums', 'diagonal-fractions', 'stacked-fractions',
    // Backgrounds
    'bg-inherit', 'bg-current', 'bg-transparent', 'bg-black', 'bg-white',
    'bg-slate-50', 'bg-slate-100', 'bg-slate-200', 'bg-slate-300', 'bg-slate-400',
    'bg-slate-500', 'bg-slate-600', 'bg-slate-700', 'bg-slate-800', 'bg-slate-900',
    'bg-gray-50', 'bg-gray-100', 'bg-gray-200', 'bg-gray-300', 'bg-gray-400',
    'bg-gray-500', 'bg-gray-600', 'bg-gray-700', 'bg-gray-800', 'bg-gray-900', 'bg-gray-950',
    'bg-red-50', 'bg-red-100', 'bg-red-200', 'bg-red-400', 'bg-red-500', 'bg-red-600', 'bg-red-700', 'bg-red-800', 'bg-red-900', 'bg-red-950',
    'bg-orange-50', 'bg-orange-100', 'bg-orange-400', 'bg-orange-500', 'bg-orange-600', 'bg-orange-900', 'bg-orange-950',
    'bg-amber-50', 'bg-amber-100', 'bg-amber-400', 'bg-amber-500', 'bg-amber-900', 'bg-amber-950',
    'bg-yellow-50', 'bg-yellow-100', 'bg-yellow-400', 'bg-yellow-500', 'bg-yellow-900',
    'bg-green-50', 'bg-green-100', 'bg-green-400', 'bg-green-500', 'bg-green-900', 'bg-green-950',
    'bg-emerald-50', 'bg-emerald-100', 'bg-emerald-400', 'bg-emerald-500', 'bg-emerald-900', 'bg-emerald-950',
    'bg-teal-50', 'bg-teal-100', 'bg-teal-400', 'bg-teal-500', 'bg-teal-900',
    'bg-cyan-50', 'bg-cyan-100', 'bg-cyan-400', 'bg-cyan-500', 'bg-cyan-900',
    'bg-sky-50', 'bg-sky-100', 'bg-sky-400', 'bg-sky-500', 'bg-sky-900',
    'bg-blue-50', 'bg-blue-100', 'bg-blue-400', 'bg-blue-500', 'bg-blue-600', 'bg-blue-900', 'bg-blue-950',
    'bg-indigo-50', 'bg-indigo-100', 'bg-indigo-400', 'bg-indigo-500', 'bg-indigo-600', 'bg-indigo-900', 'bg-indigo-950',
    'bg-violet-50', 'bg-violet-100', 'bg-violet-400', 'bg-violet-500', 'bg-violet-900',
    'bg-purple-50', 'bg-purple-100', 'bg-purple-400', 'bg-purple-500', 'bg-purple-900', 'bg-purple-950',
    'bg-pink-50', 'bg-pink-100', 'bg-pink-400', 'bg-pink-500', 'bg-pink-900',
    'bg-rose-50', 'bg-rose-100', 'bg-rose-400', 'bg-rose-500', 'bg-rose-900',
    'bg-gradient-to-t', 'bg-gradient-to-tr', 'bg-gradient-to-r', 'bg-gradient-to-br',
    'bg-gradient-to-b', 'bg-gradient-to-bl', 'bg-gradient-to-l', 'bg-gradient-to-tl',
    'from-transparent', 'from-black', 'from-white', 'from-gray-50', 'from-gray-100', 'from-gray-900',
    'from-indigo-400', 'from-indigo-500', 'from-indigo-600', 'from-purple-400', 'from-purple-500',
    'via-transparent', 'via-black', 'via-white', 'via-gray-500', 'via-indigo-500', 'via-purple-500',
    'to-transparent', 'to-black', 'to-white', 'to-gray-900', 'to-indigo-600', 'to-purple-600',
    'bg-no-repeat', 'bg-repeat', 'bg-repeat-x', 'bg-repeat-y', 'bg-repeat-round', 'bg-repeat-space',
    'bg-auto', 'bg-cover', 'bg-contain',
    'bg-fixed', 'bg-local', 'bg-scroll',
    'bg-bottom', 'bg-center', 'bg-left', 'bg-left-bottom', 'bg-left-top', 'bg-right', 'bg-right-bottom', 'bg-right-top', 'bg-top',
    'bg-clip-border', 'bg-clip-padding', 'bg-clip-content', 'bg-clip-text',
    // Borders
    'rounded-none', 'rounded-sm', 'rounded', 'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-2xl',
    'rounded-3xl', 'rounded-full',
    'rounded-t-none', 'rounded-t-sm', 'rounded-t', 'rounded-t-md', 'rounded-t-lg', 'rounded-t-xl', 'rounded-t-2xl', 'rounded-t-3xl', 'rounded-t-full',
    'rounded-r-none', 'rounded-r-sm', 'rounded-r', 'rounded-r-md', 'rounded-r-lg', 'rounded-r-xl', 'rounded-r-2xl', 'rounded-r-3xl', 'rounded-r-full',
    'rounded-b-none', 'rounded-b-sm', 'rounded-b', 'rounded-b-md', 'rounded-b-lg', 'rounded-b-xl', 'rounded-b-2xl', 'rounded-b-3xl', 'rounded-b-full',
    'rounded-l-none', 'rounded-l-sm', 'rounded-l', 'rounded-l-md', 'rounded-l-lg', 'rounded-l-xl', 'rounded-l-2xl', 'rounded-l-3xl', 'rounded-l-full',
    'border-0', 'border', 'border-2', 'border-4', 'border-8',
    'border-x-0', 'border-x', 'border-x-2', 'border-x-4', 'border-x-8',
    'border-y-0', 'border-y', 'border-y-2', 'border-y-4', 'border-y-8',
    'border-t-0', 'border-t', 'border-t-2', 'border-t-4', 'border-t-8',
    'border-r-0', 'border-r', 'border-r-2', 'border-r-4', 'border-r-8',
    'border-b-0', 'border-b', 'border-b-2', 'border-b-4', 'border-b-8',
    'border-l-0', 'border-l', 'border-l-2', 'border-l-4', 'border-l-8',
    'border-solid', 'border-dashed', 'border-dotted', 'border-double', 'border-hidden', 'border-none',
    'border-inherit', 'border-current', 'border-transparent', 'border-black', 'border-white',
    'border-gray-100', 'border-gray-200', 'border-gray-300', 'border-gray-400', 'border-gray-500',
    'border-gray-600', 'border-gray-700', 'border-gray-800', 'border-gray-900',
    'border-indigo-200', 'border-indigo-300', 'border-indigo-400', 'border-indigo-500', 'border-indigo-600',
    'border-purple-200', 'border-purple-300', 'border-purple-400', 'border-purple-500',
    'border-emerald-500', 'border-emerald-600', 'border-emerald-700',
    'border-red-500', 'border-red-600', 'border-red-700', 'border-red-800',
    'border-amber-500', 'border-amber-600', 'border-amber-700',
    'divide-x-0', 'divide-x', 'divide-x-2', 'divide-x-4', 'divide-x-8', 'divide-x-reverse',
    'divide-y-0', 'divide-y', 'divide-y-2', 'divide-y-4', 'divide-y-8', 'divide-y-reverse',
    'divide-solid', 'divide-dashed', 'divide-dotted', 'divide-double', 'divide-none',
    'divide-inherit', 'divide-current', 'divide-transparent', 'divide-black', 'divide-white',
    'divide-gray-100', 'divide-gray-200', 'divide-gray-300', 'divide-gray-700', 'divide-gray-800',
    'outline-none', 'outline', 'outline-dashed', 'outline-dotted', 'outline-double',
    'outline-0', 'outline-1', 'outline-2', 'outline-4', 'outline-8',
    'ring-0', 'ring-1', 'ring-2', 'ring-4', 'ring-8', 'ring',
    'ring-inset',
    'ring-inherit', 'ring-current', 'ring-transparent', 'ring-black', 'ring-white',
    'ring-gray-300', 'ring-gray-400', 'ring-gray-500', 'ring-gray-700', 'ring-gray-800',
    'ring-indigo-400', 'ring-indigo-500', 'ring-indigo-600',
    'ring-offset-0', 'ring-offset-1', 'ring-offset-2', 'ring-offset-4', 'ring-offset-8',
    // Effects
    'shadow-sm', 'shadow', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl', 'shadow-inner', 'shadow-none',
    'shadow-black', 'shadow-gray-900', 'shadow-indigo-500', 'shadow-purple-500',
    'opacity-0', 'opacity-5', 'opacity-10', 'opacity-20', 'opacity-25', 'opacity-30', 'opacity-40',
    'opacity-50', 'opacity-60', 'opacity-70', 'opacity-75', 'opacity-80', 'opacity-90', 'opacity-95', 'opacity-100',
    'mix-blend-normal', 'mix-blend-multiply', 'mix-blend-screen', 'mix-blend-overlay',
    'mix-blend-darken', 'mix-blend-lighten', 'mix-blend-color-dodge', 'mix-blend-color-burn',
    'mix-blend-hard-light', 'mix-blend-soft-light', 'mix-blend-difference', 'mix-blend-exclusion',
    'mix-blend-hue', 'mix-blend-saturation', 'mix-blend-color', 'mix-blend-luminosity', 'mix-blend-plus-lighter',
    'blur-none', 'blur-sm', 'blur', 'blur-md', 'blur-lg', 'blur-xl', 'blur-2xl', 'blur-3xl',
    'brightness-0', 'brightness-50', 'brightness-75', 'brightness-90', 'brightness-95', 'brightness-100',
    'brightness-105', 'brightness-110', 'brightness-125', 'brightness-150', 'brightness-200',
    'contrast-0', 'contrast-50', 'contrast-75', 'contrast-100', 'contrast-125', 'contrast-150', 'contrast-200',
    'grayscale-0', 'grayscale',
    'hue-rotate-0', 'hue-rotate-15', 'hue-rotate-30', 'hue-rotate-60', 'hue-rotate-90', 'hue-rotate-180',
    'invert-0', 'invert',
    'saturate-0', 'saturate-50', 'saturate-100', 'saturate-150', 'saturate-200',
    'sepia-0', 'sepia',
    'backdrop-blur-none', 'backdrop-blur-sm', 'backdrop-blur', 'backdrop-blur-md', 'backdrop-blur-lg',
    'backdrop-blur-xl', 'backdrop-blur-2xl', 'backdrop-blur-3xl',
    'backdrop-brightness-0', 'backdrop-brightness-50', 'backdrop-brightness-75', 'backdrop-brightness-90',
    'backdrop-brightness-95', 'backdrop-brightness-100', 'backdrop-brightness-105', 'backdrop-brightness-110',
    'backdrop-contrast-0', 'backdrop-contrast-50', 'backdrop-contrast-75', 'backdrop-contrast-100',
    'backdrop-grayscale-0', 'backdrop-grayscale',
    'backdrop-invert-0', 'backdrop-invert',
    'backdrop-opacity-0', 'backdrop-opacity-5', 'backdrop-opacity-10', 'backdrop-opacity-20',
    'backdrop-opacity-25', 'backdrop-opacity-30', 'backdrop-opacity-40', 'backdrop-opacity-50',
    'backdrop-opacity-60', 'backdrop-opacity-70', 'backdrop-opacity-75', 'backdrop-opacity-80',
    'backdrop-opacity-90', 'backdrop-opacity-95', 'backdrop-opacity-100',
    'backdrop-saturate-0', 'backdrop-saturate-50', 'backdrop-saturate-100', 'backdrop-saturate-150', 'backdrop-saturate-200',
    'backdrop-sepia-0', 'backdrop-sepia',
    // Tables
    'table-auto', 'table-fixed',
    'caption-top', 'caption-bottom',
    'border-collapse', 'border-separate',
    // Transitions & Animation
    'transition-none', 'transition-all', 'transition', 'transition-colors', 'transition-opacity',
    'transition-shadow', 'transition-transform',
    'duration-0', 'duration-75', 'duration-100', 'duration-150', 'duration-200', 'duration-300',
    'duration-500', 'duration-700', 'duration-1000',
    'ease-linear', 'ease-in', 'ease-out', 'ease-in-out',
    'delay-0', 'delay-75', 'delay-100', 'delay-150', 'delay-200', 'delay-300', 'delay-500', 'delay-700', 'delay-1000',
    'animate-none', 'animate-spin', 'animate-ping', 'animate-pulse', 'animate-bounce',
    // Transforms
    'scale-0', 'scale-50', 'scale-75', 'scale-90', 'scale-95', 'scale-100', 'scale-105', 'scale-110', 'scale-125', 'scale-150',
    'scale-x-0', 'scale-x-50', 'scale-x-75', 'scale-x-90', 'scale-x-95', 'scale-x-100', 'scale-x-105', 'scale-x-110', 'scale-x-125', 'scale-x-150',
    'scale-y-0', 'scale-y-50', 'scale-y-75', 'scale-y-90', 'scale-y-95', 'scale-y-100', 'scale-y-105', 'scale-y-110', 'scale-y-125', 'scale-y-150',
    'rotate-0', 'rotate-1', 'rotate-2', 'rotate-3', 'rotate-6', 'rotate-12', 'rotate-45', 'rotate-90', 'rotate-180',
    'translate-x-0', 'translate-x-px', 'translate-x-0.5', 'translate-x-1', 'translate-x-2', 'translate-x-3', 'translate-x-4',
    'translate-x-5', 'translate-x-6', 'translate-x-8', 'translate-x-10', 'translate-x-12', 'translate-x-16', 'translate-x-20',
    'translate-x-24', 'translate-x-32', 'translate-x-40', 'translate-x-48', 'translate-x-64', 'translate-x-full', 'translate-x-1/2',
    'translate-y-0', 'translate-y-px', 'translate-y-0.5', 'translate-y-1', 'translate-y-2', 'translate-y-3', 'translate-y-4',
    'translate-y-5', 'translate-y-6', 'translate-y-8', 'translate-y-10', 'translate-y-12', 'translate-y-16', 'translate-y-20',
    'translate-y-24', 'translate-y-32', 'translate-y-40', 'translate-y-48', 'translate-y-64', 'translate-y-full', 'translate-y-1/2',
    'skew-x-0', 'skew-x-1', 'skew-x-2', 'skew-x-3', 'skew-x-6', 'skew-x-12',
    'skew-y-0', 'skew-y-1', 'skew-y-2', 'skew-y-3', 'skew-y-6', 'skew-y-12',
    'origin-center', 'origin-top', 'origin-top-right', 'origin-right', 'origin-bottom-right',
    'origin-bottom', 'origin-bottom-left', 'origin-left', 'origin-top-left',
    // Interactivity
    'appearance-none', 'appearance-auto',
    'cursor-auto', 'cursor-default', 'cursor-pointer', 'cursor-wait', 'cursor-text', 'cursor-move',
    'cursor-help', 'cursor-not-allowed', 'cursor-none', 'cursor-context-menu', 'cursor-progress',
    'cursor-cell', 'cursor-crosshair', 'cursor-vertical-text', 'cursor-alias', 'cursor-copy',
    'cursor-no-drop', 'cursor-grab', 'cursor-grabbing', 'cursor-all-scroll',
    'cursor-col-resize', 'cursor-row-resize', 'cursor-n-resize', 'cursor-e-resize', 'cursor-s-resize',
    'cursor-w-resize', 'cursor-ne-resize', 'cursor-nw-resize', 'cursor-se-resize', 'cursor-sw-resize',
    'cursor-ew-resize', 'cursor-ns-resize', 'cursor-nesw-resize', 'cursor-nwse-resize', 'cursor-zoom-in', 'cursor-zoom-out',
    'pointer-events-none', 'pointer-events-auto',
    'resize-none', 'resize-y', 'resize-x', 'resize',
    'scroll-auto', 'scroll-smooth',
    'select-none', 'select-text', 'select-all', 'select-auto',
    'touch-auto', 'touch-none', 'touch-pan-x', 'touch-pan-left', 'touch-pan-right',
    'touch-pan-y', 'touch-pan-up', 'touch-pan-down', 'touch-pinch-zoom', 'touch-manipulation',
    'user-select-none', 'user-select-text', 'user-select-all', 'user-select-auto',
    'will-change-auto', 'will-change-scroll', 'will-change-contents', 'will-change-transform',
    // SVG
    'fill-none', 'fill-inherit', 'fill-current', 'fill-transparent', 'fill-black', 'fill-white',
    'stroke-none', 'stroke-inherit', 'stroke-current', 'stroke-transparent', 'stroke-black', 'stroke-white',
    'stroke-0', 'stroke-1', 'stroke-2',
    // Accessibility
    'sr-only', 'not-sr-only',
];

/**
 * Sort an array of Tailwind class strings by official recommended order.
 * Classes not in the list are appended at the end in their original order.
 */
export function sortTailwindClasses(classes: string[]): string[] {
    const known = new Map(TAILWIND_ORDER.map((cls, i) => [cls, i]));

    const withIndex = classes.map(cls => {
        // Strip modifiers (hover:, focus:, sm:, dark:, etc.) to find base class
        const base = cls.replace(/^[a-z-]+:/, '');
        const idx = known.get(base) ?? known.get(cls) ?? Infinity;
        return { cls, idx };
    });

    return withIndex
        .sort((a, b) => a.idx - b.idx)
        .map(x => x.cls);
}

/**
 * Extract Tailwind classes from a class string or JSX className value.
 * Handles both plain strings and template literals.
 */
export function extractClasses(input: string): string[] {
    return input
        .split(/\s+/)
        .map(s => s.trim())
        .filter(Boolean);
}